### ISSUE TITLE
Setup Reset Primary Keys

### ISSUE THREAD

**Issue by megroth2** [s2an/little-shop-7#7]
Since we want to use the ids that are pre-assigned in the .csv files, we need to tell Rails to reset primary keys (so it doesn't attempt to start from id 1 every time)

Look up "how to reset a primary key in rails"
- https://www.nikitakazakov.com/resetting-primary-key-sequence-rails
- https://railsexamples.com/reset_pk_sequence/

After each load, you have to reset the primary key for each table.

**Comment by s2an** [comment]
Completed concurrently with issue #6 (Create Rake Tasks) (with Dylan and Meg)
