### ISSUE TITLE
US-27: Admin Merchant Enable/Disable

### ISSUE THREAD

**Issue by nurudeensulaimon** [s2an/little-shop-7#72]
As an admin,
When I visit the admin merchants index (/admin/merchants)
Then next to each merchant name I see a button to disable or enable that merchant.
When I click this button
Then I am redirected back to the admin merchants index
And I see that the merchant's status has changed

**Comment by s2an** [comment]
too many merge conflicts, had to switch to: 72-us-27-admin-merchant-enabledisable-2
